# Generated by Django 6.1 on 2026-10-01 15:41

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VKPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vk_id", models.BigIntegerField(unique=True)),
                ("text", models.TextField(blank=True)),
                ("created", models.DateTimeField()),
                ("photos", models.JSONField(blank=True, default=list)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=250, unique_for_date="created"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="news_vkpost_created_181dd1_idx"
                    )
                ],
            },
        ),
    ]
