# Generated by Django 6.1 on 2026-10-04 16:14

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
